/**
 * Canonical keys for Location.seats[].category (night/day club table sections).
 * Labels are for admin dashboard display; API persists `value` strings.
 * Keep in sync with models/Location.js SeatSchema enum and Joi seatSchema.
 */
const LOCATION_SEAT_CATEGORY_OPTIONS = [
  { value: 'second_row_balcony', label: '2nd Row Balcony' },
  { value: 'second_row_premium_terrace', label: '2nd Row Premium Terrace' },
  { value: '2nd_row_premium_upper_club', label: '2nd Row Premium Upper Club' },
  { value: 'third_tier_couch', label: '3rd Tier Couch' },
  { value: 'third_tier_section', label: '3rd Tier Section' },
  { value: 'third_tier_main_room', label: 'Third Tier Main Room' },
  { value: 'four_tops', label: '4 Tops' },
  { value: 'backwall', label: 'Backwall' },
  { value: 'beach_cabana', label: 'Beach Cabana' },
  { value: 'cabana', label: 'Cabana' },
  { value: 'coastal_cabana', label: 'Coastal Cabana' },
  { value: 'grand_cabana', label: 'Grand Cabana' },
  { value: 'beach_couch', label: 'Beach Couch' },
  { value: 'beach_villa', label: 'Beach Villa' },
  { value: 'premium_beach_villa', label: 'Premium Beach Villa' },
  { value: 'villa', label: 'Villa' },
  { value: 'boardwalk_table', label: 'Boardwalk Table' },
  { value: 'ocean_bed', label: 'Ocean Bed' },
  { value: 'seaside_tables', label: 'Seaside Tables' },
  { value: 'shore_table', label: 'Shore Table' },
  { value: 'front_row_skyline_table', label: 'Front Row Skyline Table' },
  { value: 'skyline_table', label: 'Skyline Table' },
  { value: 'skybar_table', label: 'Skybar Table' },
  { value: 'center_club', label: 'Center Club' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'center_dance_floor', label: 'Center Dance Floor' },
  { value: 'center_upper_dance_floor', label: 'Center Upper Dance Floor' },
  { value: 'dance_floor', label: 'Dance Floor' },
  { value: 'dance_floor_section', label: 'Dance Floor Section' },
  { value: 'daybeds', label: 'Daybeds' },
  { value: 'driftwood_den', label: 'Driftwood Den' },
  { value: 'entry_level', label: 'Entry Level' },
  { value: 'large_3rd_tier_couch', label: 'Large 3rd Tier Couch' },
  { value: 'large_3rd_tier_section', label: 'Large 3rd Tier Section' },
  { value: 'large_side_stage_patio', label: 'Large Side Stage Patio' },
  { value: 'large_stage', label: 'Large Stage' },
  { value: 'lower_cabana', label: 'Lower Cabana' },
  { value: 'lower_club', label: 'Lower Club' },
  { value: 'lower_dance', label: 'Lower Dance' },
  { value: 'lower_dance_floor', label: 'Lower Dance Floor' },
  { value: 'owner_tables', label: 'Owner Tables' },
  { value: 'patio_section', label: 'Patio Section' },
  { value: 'platform_section', label: 'Platform Section' },
  { value: 'pool_couch', label: 'Pool Couch' },
  { value: 'pool_deck_or_lawn', label: 'Pool Deck or Lawn' },
  { value: 'poolside_section', label: 'Poolside Section' },
  { value: 'poolside_couch', label: 'Poolside Couch' },
  { value: 'premium_balcony', label: 'Premium Balcony' },
  { value: 'premium_outside_section', label: 'Premium Outside Section' },
  { value: 'premium_terrace_east', label: 'Premium Terrace East' },
  { value: 'premium_terrace_west', label: 'Premium Terrace West' },
  { value: 'premium_upper_club', label: 'Premium Upper Club' },
  { value: 'prime', label: 'Prime' },
  { value: 'prime_cabana', label: 'Prime Cabana' },
  { value: 'prime_daybed', label: 'Prime Daybed' },
  { value: 'small_1st_tier_prime', label: 'Small 1st Tier Prime' },
  { value: 'small_side_stage_patio', label: 'Small Side Stage Patio' },
  { value: 'small_stage', label: 'Small Stage' },
  { value: 'stage', label: 'Stage' },
  { value: 'stage_cabana', label: 'Stage Cabana' },
  { value: 'stage_tables', label: 'Stage Tables' },
  { value: 'standard', label: 'Standard' },
  { value: 'salon', label: 'Salon' },
  { value: 'terrace_daybed', label: 'Terrace Daybed' },
  { value: 'terrace_reserve', label: 'Terrace Reserve' },
  { value: 'terrace_table', label: 'Terrace Table' },
  { value: 'terrace_tables', label: 'Terrace Tables' },
  { value: 'terrace_strip_view', label: 'Terrace Strip View' },
  { value: 'terrace_2nd_tier', label: 'Terrace 2nd Tier' },
  { value: 'terrace_cabana', label: 'Terrace Cabana' },
  { value: 'tendai_lounge', label: 'Tendai Lounge' },
  { value: 'upper_club', label: 'Upper Club' },
  { value: 'upper_dance', label: 'Upper Dance' },
  { value: 'upper_dance_floor', label: 'Upper Dance Floor' },
  { value: 'full_upper_dance_floor', label: 'Full Upper Dance Floor' },
  { value: 'andreas_patio', label: "Andrea's Patio" },
  { value: 'backstage_section', label: 'Backstage Section' },
  { value: 'large_backstage_section', label: 'Large Backstage Section' },
  { value: 'medium_backstage_section', label: 'Medium Backstage Section' },
  { value: 'backstage_large_dance_floor', label: 'Backstage - Large Dance Floor' },
  { value: 'backstage_medium_small_dance_floor', label: 'Backstage - Medium & Small Dance Floor' },
  { value: 'backstage_small_medium_large_dance_floor', label: 'Backstage - Small, Medium & Large Dance Floor' },
  { value: 'dance_floor_water_couch', label: 'Dance Floor Water Couch' },
  { value: 'dancefloor_water_couch', label: 'Dancefloor Water Couch' },
  { value: 'daybed', label: 'Daybed' },
  { value: 'dj_dance_floor_table', label: 'DJ Dance Floor Table' },
  { value: 'dj_dance_floor_table_800', label: 'DJ Dance Floor Table 800' },
  { value: 'dj_dance_floor_table_800_pov', label: 'DJ Dance Floor Table 800 POV' },
  { value: 'floor_plan_no_platform', label: 'Floor Plan NO Platform' },
  { value: 'floor_plan_w_platform', label: 'Floor Plan W Platform' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'gaming_section', label: 'Gaming Section' },
  { value: 'gaming_pov', label: 'Gaming POV' },
  { value: 'heart_owners', label: 'Heart Owners' },
  { value: 'heart_dance_floor', label: 'Heart Dance Floor' },
  { value: 'heart_2nd_tier', label: 'Heart 2nd Tier' },
  { value: 'l_couch', label: 'L Couch' },
  { value: 'center_l_couch', label: 'Center L Couch' },
  { value: 'lily_pad', label: 'Lily Pad' },
  { value: 'center_pool_lily_pad', label: 'Center Pool Lily Pad' },
  { value: 'lotus_cabana', label: 'Lotus Cabana' },
  { value: 'bungalow', label: 'Bungalow' },
  { value: 'lower_bungalow', label: 'Lower Bungalow' },
  { value: 'lower_cabana_pov', label: 'Lower Cabana POV' },
  { value: 'main_room_owners', label: 'Main Room Owners' },
  { value: 'main_room_stage_short', label: 'Main Room Stage' },
  { value: 'main_room_dance_floor_short', label: 'Main Room Dance Floor' },
  { value: 'main_room_upper_dance_floor_short', label: 'Main Room Upper Dance Floor' },
  { value: 'main_room_lower_dance_floor', label: 'Main Room Lower Dance Floor' },
  { value: 'main_room_upper_dancefloor', label: 'Main Room Upper Dancefloor' },
  { value: 'main_room_2nd_tier', label: 'Main Room 2nd Tier' },
  { value: 'main_room_3rd_tier', label: 'Main Room 3rd Tier' },
  { value: 'main_room_balcony_large', label: 'Main Room Balcony Large' },
  { value: 'main_room_balcony_small', label: 'Main Room Balcony Small' },
  { value: 'main_room_sky_box', label: 'Main Room Sky Box' },
  { value: 'main_room_3rd_4th_rows', label: 'Main Room 3rd/4th Rows' },
  { value: 'mezzanine_center', label: 'Mezzanine Center' },
  { value: 'mezzanine_side', label: 'Mezzanine Side' },
  { value: 'mezzanine_skybox', label: 'Mezzanine Skybox' },
  { value: 'main_room_3rd_tier_u_booth', label: 'Main Room - 3rd Tier U Booth' },
  { value: 'main_room_dance_floor', label: 'Main Room - Dance Floor' },
  { value: 'main_room_owners_upper_lower_dance_floor', label: 'Main Room - Owners Upper Lower Dance Floor' },
  { value: 'main_room_shared_extended_3rd_row', label: 'Main Room - Shared Extended 3rd Row' },
  { value: 'main_room_stage', label: 'Main Room - Stage' },
  { value: 'main_room_upper_dance_floor', label: 'Main Room - Upper Dance Floor' },
  { value: 'mezzanine_center_mezzanine', label: 'Mezzanine - Center Mezzanine' },
  { value: 'mezzanine_side_mezzanine', label: 'Mezzanine - Side Mezzanine' },
  { value: 'pavilion_1st_2nd_row_pavilion', label: 'Pavilion - 1st 2nd Row Pavilion' },
  { value: 'pavilion_center_pavilion', label: 'Pavilion - Center Pavilion' },
  { value: 'pavilion_corner_pavilion', label: 'Pavilion - Corner Pavilion' },
  { value: 'platform_beach_couch', label: 'Platform Beach Couch' },
  { value: 'upper_bungalow', label: 'Upper Bungalow' },
  { value: 'water_couch', label: 'Water Couch' },
];

const LOCATION_SEAT_CATEGORY_VALUES = LOCATION_SEAT_CATEGORY_OPTIONS.map((o) => o.value);

module.exports = {
  LOCATION_SEAT_CATEGORY_OPTIONS,
  LOCATION_SEAT_CATEGORY_VALUES,
};
